import type { z } from 'zod';
import type { RobinhoodDeploymentConfig } from '@dapp-forge/blueprint-schema';
import { dedent } from '@dapp-forge/plugin-sdk';

type Config = z.infer<typeof RobinhoodDeploymentConfig>;

export function generateDeploymentGuide(config: Config): string {
  const { framework, includeExampleContract, includeVerificationSteps, includeScripts } = config;

  let content = dedent(`
    # Robinhood Chain Deployment Guide

    This guide walks through deploying smart contracts to Robinhood Chain, an Arbitrum Orbit Layer 2.
    The flow is similar to deploying to Ethereum or other Arbitrum chains.

    ## Prerequisites

    - Node.js (v18+ recommended)
    - A wallet with testnet ETH on Robinhood Chain
    - A smart contract project using Hardhat, Foundry, or another Ethereum-compatible framework

    ## Network Configuration

    Add Robinhood Chain Testnet to your development environment:

    | Parameter | Value |
    |-----------|-------|
    | Network Name | Robinhood Chain Testnet |
    | RPC URL | https://rpc.testnet.chain.robinhood.com |
    | Chain ID | 46630 |
    | Currency | ETH |
    | Block Explorer | https://explorer.testnet.chain.robinhood.com |

  `);

  if (framework === 'hardhat') {
    content += dedent(`
      ## Hardhat Setup

      ### Initialize project (if needed)

      \`\`\`bash
      mkdir rh-deploy
      cd rh-deploy
      npm init -y
      npm install --save-dev hardhat
      npx hardhat init
      \`\`\`

      ### Configure network (hardhat.config.ts)

      \`\`\`typescript
      networks: {
        robinhood: {
          url: "https://rpc.testnet.chain.robinhood.com",
          accounts: process.env.PRIVATE_KEY ? [process.env.PRIVATE_KEY] : [],
          chainId: 46630,
        },
      },
      \`\`\`

      Store your private key securely via environment variables (e.g. \`.env\`).

    `);
  } else if (framework === 'foundry') {
    content += dedent(`
      ## Foundry Setup

      ### Configure network (foundry.toml or .env)

      \`\`\`
      [rpc_endpoints]
      robinhood = "https://rpc.testnet.chain.robinhood.com"

      [etherscan]
      robinhood = { key = "\${ETHERSCAN_API_KEY}", url = "https://explorer.testnet.chain.robinhood.com/api" }
      \`\`\`

      Deploy with:

      \`\`\`bash
      forge script script/Deploy.s.sol --rpc-url robinhood --broadcast
      \`\`\`

    `);
  } else {
    content += dedent(`
      ## Network Configuration (Generic)

      Use your framework's network configuration with:

      - **RPC URL**: https://rpc.testnet.chain.robinhood.com
      - **Chain ID**: 46630

    `);
  }

  if (includeExampleContract) {
    content += dedent(`
      ## Example Contract

      Create a simple contract to deploy:

      \`\`\`solidity
      // SPDX-License-Identifier: MIT
      pragma solidity ^0.8.20;

      contract HelloRobinhood {
          function hello() external pure returns (string memory) {
              return "Hello, Robinhood Chain!";
          }
      }
      \`\`\`

    `);
  }

  if (includeScripts && framework === 'hardhat') {
    content += dedent(`
      ## Deploy Script

      \`\`\`bash
      npx hardhat run scripts/deploy.ts --network robinhood
      \`\`\`

      After deployment, you'll see the contract address in the output.

    `);
  }

  if (includeVerificationSteps) {
    content += dedent(`
      ## Verify the Contract

      To verify on the Robinhood Chain block explorer, use your tooling's verification plugin.
      Verification steps are identical to other Arbitrum chains (Hardhat Etherscan plugin, Foundry verify, etc.).

    `);
  }

  content += dedent(`
    ## Interacting With Your Contract

    After deployment you can:

    - Call contract methods using scripts or a frontend
    - Integrate with wallets that support Arbitrum-based chains
    - Monitor transactions via the [block explorer](https://explorer.testnet.chain.robinhood.com)

    ## Resources

    - [Robinhood Chain Explorer](https://explorer.testnet.chain.robinhood.com)
    - [Robinhood Chain Documentation](https://docs.robinhood.xyz)
  `);

  return content;
}

export function generateHardhatConfig(config: Config): string {
  if (config.framework !== 'hardhat') return '';

  return dedent(`
    // Robinhood Chain Hardhat Network Config
    // Generated by [N]skills - https://www.nskills.xyz

    const config = {
      robinhood: {
        url: "https://rpc.testnet.chain.robinhood.com",
        accounts: process.env.PRIVATE_KEY ? [process.env.PRIVATE_KEY] : [],
        chainId: 46630,
      },
    };

    export default config;
  `);
}

export function generateDeployScript(config: Config): string {
  if (!config.includeScripts || config.framework !== 'hardhat') return '';

  return dedent(`
    // Robinhood Chain Deploy Script
    // Generated by [N]skills - https://www.nskills.xyz

    import hre from "hardhat";

    async function main() {
      const [deployer] = await hre.ethers.getSigners();
      console.log("Deploying with account:", deployer.address);

      const HelloRobinhood = await hre.ethers.getContractFactory("HelloRobinhood");
      const contract = await HelloRobinhood.deploy();
      await contract.waitForDeployment();

      const address = await contract.getAddress();
      console.log("HelloRobinhood deployed to:", address);
    }

    main().catch((error) => {
      console.error(error);
      process.exitCode = 1;
    });
  `);
}
