import { z } from 'zod';
import {
  BasePlugin,
  type PluginMetadata,
  type PluginPort,
  type CodegenOutput,
  type BlueprintNode,
  type ExecutionContext,
} from '@dapp-forge/plugin-sdk';
import { SuperpositionNetworkConfig } from '@dapp-forge/blueprint-schema';
import {
  generateChainConfig,
  generateConstants,
  generateNetworkSwitcherHook,
  generateWagmiConfig,
  generateDocs,
} from './templates';

/**
 * Superposition Network Plugin
 * Generates chain configuration and utilities for Superposition L3
 */
export class SuperpositionNetworkPlugin extends BasePlugin<z.infer<typeof SuperpositionNetworkConfig>> {
  readonly metadata: PluginMetadata = {
    id: 'superposition-network',
    name: 'Superposition Network',
    version: '0.1.0',
    description: 'Chain configuration and network utilities for Superposition L3',
    category: 'app',
    tags: ['superposition', 'l3', 'arbitrum', 'chain-config', 'network'],
  };

  readonly configSchema = SuperpositionNetworkConfig as unknown as z.ZodType<z.infer<typeof SuperpositionNetworkConfig>>;

  readonly ports: PluginPort[] = [
    {
      id: 'chain-config-out',
      name: 'Chain Config',
      type: 'output',
      dataType: 'config',
    },
    {
      id: 'constants-out',
      name: 'Contract Constants',
      type: 'output',
      dataType: 'config',
    },
  ];

  getDefaultConfig(): Partial<z.infer<typeof SuperpositionNetworkConfig>> {
    return {
      network: 'mainnet',
      includeTestnet: true,
      generateChainConfig: true,
      generateConstants: true,
      enableWebSocket: true,
      generateNetworkSwitcher: true,
    };
  }

  async generate(
    node: BlueprintNode,
    context: ExecutionContext
  ): Promise<CodegenOutput> {
    const config = this.configSchema.parse(node.config);
    const output = this.createEmptyOutput();

    // Generate chain configuration
    if (config.generateChainConfig) {
      this.addFile(
        output,
        'chains.ts',
        generateChainConfig(config),
        'frontend-lib'
      );

      // Generate wagmi config helper
      this.addFile(
        output,
        'wagmi-superposition.ts',
        generateWagmiConfig(config),
        'frontend-lib'
      );
    }

    // Generate contract constants
    if (config.generateConstants) {
      this.addFile(
        output,
        'superposition-constants.ts',
        generateConstants(config),
        'frontend-lib'
      );
    }

    // Generate network switcher hook
    if (config.generateNetworkSwitcher) {
      this.addFile(
        output,
        'useSuperpositionNetwork.ts',
        generateNetworkSwitcherHook(config),
        'frontend-hooks'
      );
    }

    // Generate index file for easy imports
    this.addFile(
      output,
      'superposition.ts',
      generateIndexFile(config),
      'frontend-lib'
    );

    // Add environment variables
    this.addEnvVar(output, 'NEXT_PUBLIC_NETWORK', 'Superposition network (mainnet or testnet)', {
      required: false,
      defaultValue: 'mainnet',
    });

    if (config.customRpcUrl) {
      this.addEnvVar(output, 'SUPERPOSITION_RPC_URL', 'Custom Superposition RPC URL', {
        required: false,
        defaultValue: config.customRpcUrl,
      });
    }

    // Add documentation
    this.addDoc(
      output,
      'docs/superposition/network.md',
      'Superposition Network Integration',
      generateDocs(config)
    );

    context.logger.info('Generated Superposition network configuration', {
      nodeId: node.id,
      network: config.network,
      includeTestnet: config.includeTestnet,
    });

    return output;
  }
}

/**
 * Generate index file for Superposition config
 */
function generateIndexFile(config: z.infer<typeof SuperpositionNetworkConfig>): string {
  return `// Superposition Configuration Index
// Generated by [N]skills - https://www.nskills.xyz

// Chain definitions
export * from './chains';

// Contract addresses and constants
export * from './superposition-constants';

// Wagmi configuration helpers
export * from './wagmi-superposition';
`;
}
