import { z } from 'zod';
import {
  BasePlugin,
  type PluginMetadata,
  type PluginPort,
  type CodegenOutput,
  type BlueprintNode,
  type ExecutionContext,
} from '@dapp-forge/plugin-sdk';
import { SuperpositionUtilityMiningConfig } from '@dapp-forge/blueprint-schema';
import {
  generateUtilityMiningTypes,
  generateUtilityMiningConstants,
  generateUtilityMiningABIs,
  generateRewardsHook,
  generateRewardUI,
  generateLeaderboardHook,
  generateUtilityMiningDocs,
} from './templates';

/**
 * Superposition Utility Mining Plugin
 * Track and claim utility mining rewards from on-chain activity
 */
export class SuperpositionUtilityMiningPlugin extends BasePlugin<z.infer<typeof SuperpositionUtilityMiningConfig>> {
  readonly metadata: PluginMetadata = {
    id: 'superposition-utility-mining',
    name: 'Utility Mining',
    version: '0.1.0',
    description: 'Track and claim utility mining rewards from on-chain activity on Superposition',
    category: 'app',
    tags: ['superposition', 'utility-mining', 'rewards', 'trf', 'incentives'],
  };

  readonly configSchema = SuperpositionUtilityMiningConfig as unknown as z.ZodType<z.infer<typeof SuperpositionUtilityMiningConfig>>;

  readonly ports: PluginPort[] = [
    {
      id: 'network-in',
      name: 'Network Config',
      type: 'input',
      dataType: 'config',
    },
    {
      id: 'rewards-out',
      name: 'Reward Tracking',
      type: 'output',
      dataType: 'code',
    },
  ];

  getDefaultConfig(): Partial<z.infer<typeof SuperpositionUtilityMiningConfig>> {
    return {
      generateRewardTracking: true,
      generateClaimFunction: true,
      generateRewardHistory: true,
      generateUI: true,
      trackTransactionTypes: ['all'],
      includeLeaderboard: false,
    };
  }

  async generate(
    node: BlueprintNode,
    context: ExecutionContext
  ): Promise<CodegenOutput> {
    const config = this.configSchema.parse(node.config);
    const output = this.createEmptyOutput();

    const typesDir = 'src/types';
    const configDir = 'src/config';
    const hooksDir = 'src/hooks';
    const componentsDir = 'src/components';

    // Generate types
    this.addFile(output, `${typesDir}/utility-mining.ts`, generateUtilityMiningTypes());

    // Generate constants and ABIs
    this.addFile(output, `${configDir}/utility-mining-constants.ts`, generateUtilityMiningConstants());
    this.addFile(output, `${configDir}/utility-mining-abi.ts`, generateUtilityMiningABIs());

    // Generate rewards tracking hook
    if (config.generateRewardTracking) {
      this.addFile(
        output,
        `${hooksDir}/useUtilityMiningRewards.ts`,
        generateRewardsHook(config)
      );
    }

    // Generate leaderboard hook
    if (config.includeLeaderboard) {
      this.addFile(
        output,
        `${hooksDir}/useUtilityMiningLeaderboard.ts`,
        generateLeaderboardHook()
      );
    }

    // Generate UI component
    if (config.generateUI) {
      this.addFile(
        output,
        `${componentsDir}/UtilityMiningRewardDisplay.tsx`,
        generateRewardUI()
      );
    }

    // Generate index file
    this.addFile(
      output,
      `${configDir}/utility-mining-index.ts`,
      generateIndexFile(config)
    );

    // Add documentation
    this.addDoc(
      output,
      'docs/superposition/utility-mining.md',
      'Superposition Utility Mining',
      generateUtilityMiningDocs(config)
    );

    context.logger.info('Generated Superposition Utility Mining integration', {
      nodeId: node.id,
      trackTransactionTypes: config.trackTransactionTypes,
    });

    return output;
  }
}

/**
 * Generate index file for Utility Mining exports
 */
function generateIndexFile(config: z.infer<typeof SuperpositionUtilityMiningConfig>): string {
  return `// Superposition Utility Mining - Index
// Generated by Cradle - https://cradle.dev

// Configuration
export * from './utility-mining-constants';
export * from './utility-mining-abi';

// Types
export * from '../types/utility-mining';
`;
}
