import { z } from 'zod';
import {
  BasePlugin,
  type PluginMetadata,
  type PluginPort,
  type CodegenOutput,
  type BlueprintNode,
  type ExecutionContext,
} from '@dapp-forge/plugin-sdk';
import { SuperpositionFaucetConfig } from '@dapp-forge/blueprint-schema';
import {
  generateFaucetTypes,
  generateFaucetConstants,
  generateFaucetHook,
  generateFaucetUI,
  generateBalanceHook,
  generateFaucetDocs,
} from './templates';

/**
 * Superposition Faucet Plugin
 * Request testnet tokens for development and testing
 */
export class SuperpositionFaucetPlugin extends BasePlugin<z.infer<typeof SuperpositionFaucetConfig>> {
  readonly metadata: PluginMetadata = {
    id: 'superposition-faucet',
    name: 'Testnet Faucet',
    version: '0.1.0',
    description: 'Request testnet tokens (SPN, wSPN, CAT, fUSDC) for development on Superposition',
    category: 'app',
    tags: ['superposition', 'faucet', 'testnet', 'development', 'tokens'],
  };

  readonly configSchema = SuperpositionFaucetConfig as unknown as z.ZodType<z.infer<typeof SuperpositionFaucetConfig>>;

  readonly ports: PluginPort[] = [
    {
      id: 'network-in',
      name: 'Network Config',
      type: 'input',
      dataType: 'config',
    },
    {
      id: 'faucet-out',
      name: 'Faucet Integration',
      type: 'output',
      dataType: 'code',
    },
  ];

  getDefaultConfig(): Partial<z.infer<typeof SuperpositionFaucetConfig>> {
    return {
      tokens: ['SPN', 'fUSDC'],
      generateFaucetHook: true,
      generateFaucetUI: true,
      includeCooldownTimer: true,
      includeBalanceCheck: true,
    };
  }

  async generate(
    node: BlueprintNode,
    context: ExecutionContext
  ): Promise<CodegenOutput> {
    const config = this.configSchema.parse(node.config);
    const output = this.createEmptyOutput();

    const typesDir = 'src/types';
    const configDir = 'src/config';
    const hooksDir = 'src/hooks';
    const componentsDir = 'src/components';

    // Generate types
    this.addFile(output, `${typesDir}/faucet.ts`, generateFaucetTypes());

    // Generate constants
    this.addFile(output, `${configDir}/faucet-constants.ts`, generateFaucetConstants());

    // Generate faucet hook
    if (config.generateFaucetHook) {
      this.addFile(
        output,
        `${hooksDir}/useSuperpositionFaucet.ts`,
        generateFaucetHook(config)
      );
    }

    // Generate faucet UI
    if (config.generateFaucetUI) {
      this.addFile(
        output,
        `${componentsDir}/SuperpositionFaucet.tsx`,
        generateFaucetUI(config)
      );
    }

    // Generate balance check hook
    if (config.includeBalanceCheck) {
      this.addFile(
        output,
        `${hooksDir}/useTestnetBalances.ts`,
        generateBalanceHook()
      );
    }

    // Generate index file
    this.addFile(
      output,
      `${configDir}/faucet-index.ts`,
      generateIndexFile(config)
    );

    // Add documentation
    this.addDoc(
      output,
      'docs/superposition/faucet.md',
      'Superposition Testnet Faucet',
      generateFaucetDocs(config)
    );

    context.logger.info('Generated Superposition Faucet integration', {
      nodeId: node.id,
      tokens: config.tokens,
    });

    return output;
  }
}

/**
 * Generate index file for Faucet exports
 */
function generateIndexFile(config: z.infer<typeof SuperpositionFaucetConfig>): string {
  return `// Superposition Faucet - Index
// Generated by Cradle - https://cradle.dev

// Configuration
export * from './faucet-constants';

// Types
export * from '../types/faucet';
`;
}
