import { z } from 'zod';
import {
  BasePlugin,
  type PluginMetadata,
  type PluginPort,
  type CodegenOutput,
  type BlueprintNode,
  type ExecutionContext,
} from '@dapp-forge/plugin-sdk';
import { SuperpositionFaucetConfig } from '@dapp-forge/blueprint-schema';
import {
  generateFaucetTypes,
  generateFaucetConstants,
  generateFaucetHook,
  generateFaucetUI,
  generateBalanceHook,
  generateFaucetDocs,
} from './templates';

/**
 * Superposition Faucet Plugin
 * Request testnet tokens for development and testing
 */
export class SuperpositionFaucetPlugin extends BasePlugin<z.infer<typeof SuperpositionFaucetConfig>> {
  readonly metadata: PluginMetadata = {
    id: 'superposition-faucet',
    name: 'Testnet Faucet',
    version: '0.1.0',
    description: 'Request testnet tokens (SPN, wSPN, CAT, fUSDC) for development on Superposition',
    category: 'app',
    tags: ['superposition', 'faucet', 'testnet', 'development', 'tokens'],
  };

  readonly configSchema = SuperpositionFaucetConfig as unknown as z.ZodType<z.infer<typeof SuperpositionFaucetConfig>>;

  readonly ports: PluginPort[] = [
    {
      id: 'network-in',
      name: 'Network Config',
      type: 'input',
      dataType: 'config',
    },
    {
      id: 'faucet-out',
      name: 'Faucet Integration',
      type: 'output',
      dataType: 'code',
    },
  ];

  getDefaultConfig(): Partial<z.infer<typeof SuperpositionFaucetConfig>> {
    return {
      tokens: ['SPN', 'fUSDC'],
      generateFaucetHook: true,
      generateFaucetUI: true,
      includeCooldownTimer: true,
      includeBalanceCheck: true,
    };
  }

  async generate(
    node: BlueprintNode,
    context: ExecutionContext
  ): Promise<CodegenOutput> {
    const config = this.configSchema.parse(node.config);
    const output = this.createEmptyOutput();

    // Generate types
    this.addFile(output, 'faucet.ts', generateFaucetTypes(), 'frontend-types');

    // Generate constants
    this.addFile(output, 'faucet-constants.ts', generateFaucetConstants(), 'frontend-lib');

    // Generate faucet hook
    if (config.generateFaucetHook) {
      this.addFile(output, 'useSuperpositionFaucet.ts', generateFaucetHook(config), 'frontend-hooks');
    }

    // Generate faucet UI
    if (config.generateFaucetUI) {
      this.addFile(output, 'SuperpositionFaucet.tsx', generateFaucetUI(config), 'frontend-components');
    }

    // Generate balance check hook
    if (config.includeBalanceCheck) {
      this.addFile(output, 'useTestnetBalances.ts', generateBalanceHook(), 'frontend-hooks');
    }

    // Generate index file
    this.addFile(output, 'faucet-index.ts', generateIndexFile(config), 'frontend-lib');

    // Add documentation
    this.addDoc(
      output,
      'docs/superposition/faucet.md',
      'Superposition Testnet Faucet',
      generateFaucetDocs(config)
    );

    context.logger.info('Generated Superposition Faucet integration', {
      nodeId: node.id,
      tokens: config.tokens,
    });

    return output;
  }
}

/**
 * Generate index file for Faucet exports
 */
function generateIndexFile(config: z.infer<typeof SuperpositionFaucetConfig>): string {
  return `// Superposition Faucet - Index
// Generated by [N]skills - https://www.nskills.xyz

// Configuration
export * from './faucet-constants';

// Types
export * from '../types/faucet';
`;
}
