import type { z } from 'zod';
import type { SuperpositionFaucetConfig } from '@dapp-forge/blueprint-schema';
import { dedent } from '@dapp-forge/plugin-sdk';

type Config = z.infer<typeof SuperpositionFaucetConfig>;

/**
 * Generate Faucet types
 */
export function generateFaucetTypes(): string {
  return dedent(`
    // Superposition Faucet Types
    // Generated by Cradle - https://cradle-web-eight.vercel.app

    export type FaucetToken = 'SPN' | 'wSPN' | 'CAT' | 'fUSDC';

    export interface TokenInfo {
      symbol: FaucetToken;
      name: string;
      amount: string;
      decimals: number;
    }

    export interface FaucetRequest {
      token: FaucetToken;
      address: string;
      timestamp: number;
    }

    export interface FaucetResponse {
      success: boolean;
      transactionHash?: string;
      message?: string;
      nextAvailable?: number;
    }

    export interface CooldownStatus {
      canRequest: boolean;
      nextAvailable: number | null;
      remainingSeconds: number;
    }

    export type FaucetStatus = 'idle' | 'checking' | 'requesting' | 'success' | 'cooldown' | 'error';

    export interface UseFaucetReturn {
      status: FaucetStatus;
      error: Error | null;
      cooldown: CooldownStatus;
      lastTxHash: string | null;
      isLoading: boolean;
      requestTokens: (token?: FaucetToken) => Promise<FaucetResponse>;
      checkCooldown: () => Promise<CooldownStatus>;
      supportedTokens: TokenInfo[];
    }
  `);
}

/**
 * Generate Faucet constants
 */
export function generateFaucetConstants(): string {
  return dedent(`
    // Superposition Faucet Constants
    // Generated by Cradle - https://cradle-web-eight.vercel.app

    import type { FaucetToken, TokenInfo } from '../types/faucet';

    /**
     * Faucet configuration
     */
    export const FAUCET_CONFIG = {
      // Faucet URLs
      testnetFaucetUrl: 'https://faucet.superposition.so',
      faucetApiUrl: 'https://faucet-api.superposition.so',
      
      // Cooldown period (5 hours in seconds)
      cooldownPeriod: 5 * 60 * 60,
      
      // Request endpoints
      endpoints: {
        request: '/api/request',
        status: '/api/status',
        cooldown: '/api/cooldown',
      },
    } as const;

    /**
     * Supported tokens and their amounts
     */
    export const FAUCET_TOKENS: Record<FaucetToken, TokenInfo> = {
      SPN: {
        symbol: 'SPN',
        name: 'Superposition Native Token',
        amount: '0.5',
        decimals: 18,
      },
      wSPN: {
        symbol: 'wSPN',
        name: 'Wrapped SPN',
        amount: '0.5',
        decimals: 18,
      },
      CAT: {
        symbol: 'CAT',
        name: 'CAT Token',
        amount: '100',
        decimals: 18,
      },
      fUSDC: {
        symbol: 'fUSDC',
        name: 'Faucet USDC',
        amount: '0.5',
        decimals: 6,
      },
    } as const;

    /**
     * Testnet chain configuration
     */
    export const TESTNET_CONFIG = {
      chainId: 98985,
      name: 'Superposition Testnet',
      rpcUrl: 'https://testnet-rpc.superposition.so',
      explorerUrl: 'https://testnet-explorer.superposition.so',
    } as const;

    /**
     * Token addresses on testnet (verified from docs.long.so and Superposition docs)
     */
    export const TESTNET_TOKEN_ADDRESSES = {
      // Faucet contract (verified from Superposition docs)
      FAUCET: '0xD1919257706d044f5c218142110431885792bc2B',
      
      // Token addresses (verified from docs.long.so)
      wSPN: '0x22b9fa698b68bBA071B513959794E9a47d19214c',
      fUSDC: '0xA8EA92c819463EFbEdDFB670FEfC881A480f0115',
      WETH: '0xde104342B32BCa03ec995f999181f7Cf1fFc04d7',
      USDC: '0x6437fdc89cED41941b97A9f1f8992D88718C81c5',
      CATBUX: '0x36c116a8851869cf8a99b3Bda0Fad42453D32B99',
    } as const;
  `);
}

/**
 * Generate Faucet hook
 */
export function generateFaucetHook(config: Config): string {
  const tokens = config.tokens.includes('all')
    ? ['SPN', 'wSPN', 'CAT', 'fUSDC']
    : config.tokens;

  return dedent(`
    // Superposition Faucet Hook
    // Generated by Cradle - https://cradle-web-eight.vercel.app

    'use client';

    import { useState, useCallback, useEffect, useMemo } from 'react';
    import { useAccount } from 'wagmi';
    import { FAUCET_CONFIG, FAUCET_TOKENS } from '../lib/faucet-constants';
    import type {
      FaucetToken,
      FaucetResponse,
      CooldownStatus,
      FaucetStatus,
      UseFaucetReturn,
      TokenInfo,
    } from '../types/faucet';

    // Local storage key for tracking cooldown
    const COOLDOWN_KEY = 'superposition_faucet_cooldown';

    interface UseFaucetOptions {
      defaultToken?: FaucetToken;
    }

    /**
     * Hook for requesting testnet tokens from the Superposition faucet
     */
    export function useSuperpositionFaucet(
      options: UseFaucetOptions = {}
    ): UseFaucetReturn {
      const { defaultToken = 'SPN' } = options;
      const { address, isConnected } = useAccount();

      const [status, setStatus] = useState<FaucetStatus>('idle');
      const [error, setError] = useState<Error | null>(null);
      const [cooldown, setCooldown] = useState<CooldownStatus>({
        canRequest: true,
        nextAvailable: null,
        remainingSeconds: 0,
      });
      const [lastTxHash, setLastTxHash] = useState<string | null>(null);

      const isLoading = status === 'checking' || status === 'requesting';

      // Supported tokens based on configuration
      const supportedTokens: TokenInfo[] = useMemo(() => {
        const tokenList: FaucetToken[] = ${JSON.stringify(tokens)};
        return tokenList.map((t) => FAUCET_TOKENS[t]);
      }, []);

      /**
       * Check cooldown status
       */
      const checkCooldown = useCallback(async (): Promise<CooldownStatus> => {
        if (!address) {
          return { canRequest: false, nextAvailable: null, remainingSeconds: 0 };
        }

        setStatus('checking');

        try {
          // Check local storage first for quick response
          const stored = localStorage.getItem(\`\${COOLDOWN_KEY}_\${address}\`);
          if (stored) {
            const lastRequest = parseInt(stored, 10);
            const nextAvailable = lastRequest + FAUCET_CONFIG.cooldownPeriod * 1000;
            const now = Date.now();

            if (now < nextAvailable) {
              const remainingSeconds = Math.ceil((nextAvailable - now) / 1000);
              const cooldownStatus: CooldownStatus = {
                canRequest: false,
                nextAvailable,
                remainingSeconds,
              };
              setCooldown(cooldownStatus);
              setStatus('cooldown');
              return cooldownStatus;
            }
          }

          // Also check with the faucet API
          const response = await fetch(
            \`\${FAUCET_CONFIG.faucetApiUrl}\${FAUCET_CONFIG.endpoints.cooldown}?address=\${address}\`
          );

          if (response.ok) {
            const data = await response.json();
            const cooldownStatus: CooldownStatus = {
              canRequest: data.canRequest,
              nextAvailable: data.nextAvailable,
              remainingSeconds: data.remainingSeconds || 0,
            };
            setCooldown(cooldownStatus);
            setStatus(data.canRequest ? 'idle' : 'cooldown');
            return cooldownStatus;
          }

          // If API fails, fall back to allowing request
          const defaultStatus: CooldownStatus = { canRequest: true, nextAvailable: null, remainingSeconds: 0 };
          setCooldown(defaultStatus);
          setStatus('idle');
          return defaultStatus;
        } catch (err) {
          // On error, allow request (faucet will handle validation)
          const defaultStatus: CooldownStatus = { canRequest: true, nextAvailable: null, remainingSeconds: 0 };
          setCooldown(defaultStatus);
          setStatus('idle');
          return defaultStatus;
        }
      }, [address]);

      /**
       * Request tokens from the faucet
       */
      const requestTokens = useCallback(
        async (token: FaucetToken = defaultToken): Promise<FaucetResponse> => {
          if (!address) {
            throw new Error('Wallet not connected');
          }

          if (!cooldown.canRequest) {
            throw new Error(\`Please wait \${formatTime(cooldown.remainingSeconds)} before requesting again\`);
          }

          setStatus('requesting');
          setError(null);

          try {
            const response = await fetch(
              \`\${FAUCET_CONFIG.faucetApiUrl}\${FAUCET_CONFIG.endpoints.request}\`,
              {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                  address,
                  token,
                }),
              }
            );

            const data = await response.json();

            if (!response.ok || !data.success) {
              throw new Error(data.message || 'Faucet request failed');
            }

            // Store request time for cooldown tracking
            localStorage.setItem(\`\${COOLDOWN_KEY}_\${address}\`, Date.now().toString());

            setLastTxHash(data.transactionHash || null);
            setStatus('success');

            // Update cooldown status
            setCooldown({
              canRequest: false,
              nextAvailable: Date.now() + FAUCET_CONFIG.cooldownPeriod * 1000,
              remainingSeconds: FAUCET_CONFIG.cooldownPeriod,
            });

            return data;
          } catch (err) {
            const error = err instanceof Error ? err : new Error('Faucet request failed');
            setError(error);
            setStatus('error');
            throw error;
          }
        },
        [address, cooldown, defaultToken]
      );

      // Check cooldown on mount and when address changes
      useEffect(() => {
        if (isConnected && address) {
          checkCooldown();
        }
      }, [isConnected, address, checkCooldown]);

      // Update remaining seconds periodically when in cooldown
      useEffect(() => {
        if (!cooldown.nextAvailable || cooldown.canRequest) return;

        const interval = setInterval(() => {
          const now = Date.now();
          const remaining = Math.max(0, Math.ceil((cooldown.nextAvailable! - now) / 1000));

          if (remaining === 0) {
            setCooldown({ canRequest: true, nextAvailable: null, remainingSeconds: 0 });
            setStatus('idle');
          } else {
            setCooldown((prev) => ({ ...prev, remainingSeconds: remaining }));
          }
        }, 1000);

        return () => clearInterval(interval);
      }, [cooldown.nextAvailable, cooldown.canRequest]);

      return {
        status,
        error,
        cooldown,
        lastTxHash,
        isLoading,
        requestTokens,
        checkCooldown,
        supportedTokens,
      };
    }

    /**
     * Format seconds into human-readable time
     */
    function formatTime(seconds: number): string {
      const hours = Math.floor(seconds / 3600);
      const minutes = Math.floor((seconds % 3600) / 60);
      const secs = seconds % 60;

      if (hours > 0) {
        return \`\${hours}h \${minutes}m\`;
      }
      if (minutes > 0) {
        return \`\${minutes}m \${secs}s\`;
      }
      return \`\${secs}s\`;
    }
  `);
}

/**
 * Generate Faucet UI component
 */
export function generateFaucetUI(config: Config): string {
  return dedent(`
    // Superposition Faucet UI Component
    // Generated by Cradle - https://cradle-web-eight.vercel.app

    'use client';

    import { useState } from 'react';
    import { useSuperpositionFaucet } from '../hooks/useSuperpositionFaucet';
    import { TESTNET_CONFIG } from '../lib/faucet-constants';
    import type { FaucetToken } from '../types/faucet';

    interface FaucetUIProps {
      className?: string;
      onSuccess?: (txHash: string) => void;
    }

    /**
     * Faucet UI Component for requesting testnet tokens
     */
    export function SuperpositionFaucet({ className = '', onSuccess }: FaucetUIProps) {
      const {
        status,
        error,
        cooldown,
        lastTxHash,
        isLoading,
        requestTokens,
        supportedTokens,
      } = useSuperpositionFaucet();

      const [selectedToken, setSelectedToken] = useState<FaucetToken>('SPN');

      const handleRequest = async () => {
        try {
          const result = await requestTokens(selectedToken);
          if (result.transactionHash && onSuccess) {
            onSuccess(result.transactionHash);
          }
        } catch (err) {
          console.error('Faucet request failed:', err);
        }
      };

      const formatTime = (seconds: number): string => {
        const hours = Math.floor(seconds / 3600);
        const minutes = Math.floor((seconds % 3600) / 60);
        const secs = seconds % 60;
        if (hours > 0) return \`\${hours}h \${minutes}m\`;
        if (minutes > 0) return \`\${minutes}m \${secs}s\`;
        return \`\${secs}s\`;
      };

      return (
        <div className={\`superposition-faucet \${className}\`}>
          <h3>Superposition Testnet Faucet</h3>
          <p className="faucet-description">
            Get testnet tokens to start building on Superposition.
          </p>

          <div className="token-selector">
            <label htmlFor="token-select">Select Token:</label>
            <select
              id="token-select"
              value={selectedToken}
              onChange={(e) => setSelectedToken(e.target.value as FaucetToken)}
              disabled={isLoading || !cooldown.canRequest}
            >
              {supportedTokens.map((token) => (
                <option key={token.symbol} value={token.symbol}>
                  {token.symbol} - {token.amount} {token.symbol}
                </option>
              ))}
            </select>
          </div>

          <div className="token-info">
            <h4>You will receive:</h4>
            <ul>
              <li>0.5 SPN (native token)</li>
              <li>0.5 wSPN (wrapped SPN)</li>
              <li>100 CAT</li>
              <li>0.5 fUSDC</li>
            </ul>
          </div>

          {!cooldown.canRequest && (
            <div className="cooldown-notice">
              <p>⏱️ Next request available in: {formatTime(cooldown.remainingSeconds)}</p>
            </div>
          )}

          {error && (
            <div className="error-message">
              <p>❌ {error.message}</p>
            </div>
          )}

          {status === 'success' && lastTxHash && (
            <div className="success-message">
              <p>✅ Tokens sent successfully!</p>
              <a
                href={\`\${TESTNET_CONFIG.explorerUrl}/tx/\${lastTxHash}\`}
                target="_blank"
                rel="noopener noreferrer"
              >
                View Transaction
              </a>
            </div>
          )}

          <button
            onClick={handleRequest}
            disabled={isLoading || !cooldown.canRequest}
            className="request-button"
          >
            {isLoading
              ? 'Requesting...'
              : !cooldown.canRequest
              ? \`Wait \${formatTime(cooldown.remainingSeconds)}\`
              : 'Request Testnet Tokens'}
          </button>

          <div className="faucet-links">
            <a
              href={TESTNET_CONFIG.explorerUrl}
              target="_blank"
              rel="noopener noreferrer"
            >
              Testnet Explorer
            </a>
            <a
              href="https://docs.superposition.so"
              target="_blank"
              rel="noopener noreferrer"
            >
              Documentation
            </a>
          </div>
        </div>
      );
    }

    export default SuperpositionFaucet;
  `);
}

/**
 * Generate balance check hook
 */
export function generateBalanceHook(): string {
  return dedent(`
    // Superposition Testnet Balance Hook
    // Generated by Cradle - https://cradle-web-eight.vercel.app

    'use client';

    import { useAccount, useBalance } from 'wagmi';
    import { TESTNET_CONFIG, TESTNET_TOKEN_ADDRESSES } from '../lib/faucet-constants';
    import type { FaucetToken } from '../types/faucet';

    interface TokenBalance {
      token: FaucetToken;
      balance: bigint;
      formatted: string;
      symbol: string;
    }

    interface UseTestnetBalancesReturn {
      balances: Record<FaucetToken, TokenBalance | null>;
      isLoading: boolean;
      refetch: () => void;
    }

    /**
     * Hook for checking testnet token balances
     */
    export function useTestnetBalances(): UseTestnetBalancesReturn {
      const { address } = useAccount();

      // Native SPN balance
      const { data: spnBalance, isLoading: spnLoading, refetch: refetchSpn } = useBalance({
        address,
        chainId: TESTNET_CONFIG.chainId,
      });

      // wSPN balance
      const { data: wspnBalance, isLoading: wspnLoading, refetch: refetchWspn } = useBalance({
        address,
        token: TESTNET_TOKEN_ADDRESSES.wSPN as \`0x\${string}\`,
        chainId: TESTNET_CONFIG.chainId,
      });

      const isLoading = spnLoading || wspnLoading;

      const refetch = () => {
        refetchSpn();
        refetchWspn();
      };

      const balances: Record<FaucetToken, TokenBalance | null> = {
        SPN: spnBalance ? {
          token: 'SPN',
          balance: spnBalance.value,
          formatted: spnBalance.formatted,
          symbol: spnBalance.symbol,
        } : null,
        wSPN: wspnBalance ? {
          token: 'wSPN',
          balance: wspnBalance.value,
          formatted: wspnBalance.formatted,
          symbol: wspnBalance.symbol,
        } : null,
        // CAT token: 0x36c116a8851869cf8a99b3Bda0Fad42453D32B99
        CAT: null,
        // fUSDC token: 0xA8EA92c819463EFbEdDFB670FEfC881A480f0115
        fUSDC: null,
      };

      return {
        balances,
        isLoading,
        refetch,
      };
    }
  `);
}

/**
 * Generate documentation
 */
export function generateFaucetDocs(config: Config): string {
  return dedent(`
    # Superposition Testnet Faucet

    Request testnet tokens for development and testing on Superposition.

    ## Overview

    The Superposition Faucet provides free testnet tokens for developers to test their applications before deploying to mainnet.

    ### Available Tokens

    | Token | Amount | Description |
    |-------|--------|-------------|
    | SPN | 0.5 | Native testnet token |
    | wSPN | 0.5 | Wrapped SPN |
    | CAT | 100 | CAT Token |
    | fUSDC | 0.5 | Faucet USDC |

    ### Cooldown Period

    You can request tokens once every **5 hours** per wallet address.

    ## Usage

    ### Basic Usage

    \`\`\`typescript
    import { useSuperpositionFaucet } from './hooks/useSuperpositionFaucet';

    function FaucetButton() {
      const { requestTokens, cooldown, isLoading } = useSuperpositionFaucet();

      const handleRequest = async () => {
        try {
          const result = await requestTokens('SPN');
          console.log('TX Hash:', result.transactionHash);
        } catch (error) {
          console.error('Failed:', error.message);
        }
      };

      return (
        <button onClick={handleRequest} disabled={isLoading || !cooldown.canRequest}>
          {cooldown.canRequest ? 'Get Testnet Tokens' : \`Wait \${cooldown.remainingSeconds}s\`}
        </button>
      );
    }
    \`\`\`

    ### Use the Pre-built Component

    \`\`\`tsx
    import { SuperpositionFaucet } from './components/SuperpositionFaucet';

    function App() {
      return (
        <SuperpositionFaucet
          onSuccess={(txHash) => console.log('Tokens received!', txHash)}
        />
      );
    }
    \`\`\`

    ${config.includeBalanceCheck ? `
    ### Check Balances

    \`\`\`typescript
    import { useTestnetBalances } from './hooks/useTestnetBalances';

    function BalanceDisplay() {
      const { balances, isLoading } = useTestnetBalances();

      return (
        <div>
          <p>SPN: {balances.SPN?.formatted ?? '0'}</p>
          <p>wSPN: {balances.wSPN?.formatted ?? '0'}</p>
        </div>
      );
    }
    \`\`\`
    ` : ''}

    ## Network Details

    - **Chain ID**: 98985
    - **RPC URL**: https://testnet-rpc.superposition.so
    - **Explorer**: https://testnet-explorer.superposition.so
    - **Faucet**: https://faucet.superposition.so

    ## Resources

    - [Superposition Faucet](https://faucet.superposition.so)
    - [Superposition Documentation](https://docs.superposition.so)
  `);
}
