import { z } from 'zod';
import {
  BasePlugin,
  type PluginMetadata,
  type PluginPort,
  type CodegenOutput,
  type BlueprintNode,
  type ExecutionContext,
} from '@dapp-forge/plugin-sdk';
import { SuperpositionThirdwebConfig } from '@dapp-forge/blueprint-schema';
import {
  generateThirdwebTypes,
  generateThirdwebConfig,
  generateDeployHook,
  generateContractHook,
  generateThirdwebProvider,
  generatePrebuiltContracts,
  generateThirdwebDocs,
} from './templates';

/**
 * Superposition Thirdweb Plugin
 * Deploy and interact with contracts using Thirdweb SDK on Superposition
 */
export class SuperpositionThirdwebPlugin extends BasePlugin<z.infer<typeof SuperpositionThirdwebConfig>> {
  readonly metadata: PluginMetadata = {
    id: 'superposition-thirdweb',
    name: 'Thirdweb on Superposition',
    version: '0.1.0',
    description: 'Deploy and interact with smart contracts using Thirdweb SDK on Superposition L3',
    category: 'app',
    tags: ['superposition', 'thirdweb', 'contracts', 'deploy', 'nft', 'token'],
  };

  readonly configSchema = SuperpositionThirdwebConfig as unknown as z.ZodType<z.infer<typeof SuperpositionThirdwebConfig>>;

  readonly ports: PluginPort[] = [
    {
      id: 'network-in',
      name: 'Network Config',
      type: 'input',
      dataType: 'config',
    },
    {
      id: 'thirdweb-out',
      name: 'Thirdweb Config',
      type: 'output',
      dataType: 'config',
    },
    {
      id: 'contracts-out',
      name: 'Contract Helpers',
      type: 'output',
      dataType: 'api',
    },
  ];

  getDefaultConfig(): Partial<z.infer<typeof SuperpositionThirdwebConfig>> {
    return {
      features: ['deploy-contract', 'contract-interaction'],
      generateThirdwebProvider: true,
      generateDeployHelpers: true,
      generateContractHooks: true,
      includePrebuiltContracts: true,
      gasless: false,
    };
  }

  async generate(
    node: BlueprintNode,
    context: ExecutionContext
  ): Promise<CodegenOutput> {
    const config = this.configSchema.parse(node.config);
    const output = this.createEmptyOutput();

    const typesDir = 'src/types';
    const configDir = 'src/config';
    const hooksDir = 'src/hooks';
    const providersDir = 'src/providers';

    // Generate types
    this.addFile(output, `${typesDir}/thirdweb.ts`, generateThirdwebTypes());

    // Generate Thirdweb configuration
    this.addFile(output, `${configDir}/thirdweb.ts`, generateThirdwebConfig());

    // Generate deploy hook
    if (config.generateDeployHelpers) {
      this.addFile(
        output,
        `${hooksDir}/useThirdwebSuperposition.ts`,
        generateDeployHook(config)
      );
    }

    // Generate contract interaction hook
    if (config.generateContractHooks) {
      this.addFile(
        output,
        `${hooksDir}/useSuperpositionContract.ts`,
        generateContractHook()
      );
    }

    // Generate provider component
    if (config.generateThirdwebProvider) {
      this.addFile(
        output,
        `${providersDir}/SuperpositionThirdwebProvider.tsx`,
        generateThirdwebProvider()
      );
    }

    // Generate prebuilt contracts helpers
    if (config.includePrebuiltContracts) {
      this.addFile(
        output,
        `${configDir}/prebuilt-contracts.ts`,
        generatePrebuiltContracts()
      );
    }

    // Generate index file
    this.addFile(
      output,
      `${configDir}/thirdweb-index.ts`,
      generateIndexFile(config)
    );

    // Add environment variables
    this.addEnvVar(
      output,
      'NEXT_PUBLIC_THIRDWEB_CLIENT_ID',
      'Thirdweb client ID from https://thirdweb.com/dashboard',
      { required: true }
    );

    // Add documentation
    this.addDoc(
      output,
      'docs/superposition/thirdweb.md',
      'Thirdweb on Superposition',
      generateThirdwebDocs(config)
    );

    context.logger.info('Generated Thirdweb on Superposition integration', {
      nodeId: node.id,
      features: config.features,
    });

    return output;
  }
}

/**
 * Generate index file for Thirdweb exports
 */
function generateIndexFile(config: z.infer<typeof SuperpositionThirdwebConfig>): string {
  return `// Thirdweb on Superposition - Index
// Generated by Cradle - https://cradle.dev

// Configuration
export * from './thirdweb';
${config.includePrebuiltContracts ? "export * from './prebuilt-contracts';" : ''}

// Types
export * from '../types/thirdweb';
`;
}
