import { z } from 'zod';
import {
  BasePlugin,
  type PluginMetadata,
  type PluginPort,
  type CodegenOutput,
  type BlueprintNode,
  type ExecutionContext,
} from '@dapp-forge/plugin-sdk';
import { SuperpositionThirdwebConfig } from '@dapp-forge/blueprint-schema';
import {
  generateThirdwebTypes,
  generateThirdwebConfig,
  generateDeployHook,
  generateContractHook,
  generateThirdwebProvider,
  generatePrebuiltContracts,
  generateThirdwebDocs,
} from './templates';

/**
 * Superposition Thirdweb Plugin
 * Deploy and interact with contracts using Thirdweb SDK on Superposition
 */
export class SuperpositionThirdwebPlugin extends BasePlugin<z.infer<typeof SuperpositionThirdwebConfig>> {
  readonly metadata: PluginMetadata = {
    id: 'superposition-thirdweb',
    name: 'Thirdweb on Superposition',
    version: '0.1.0',
    description: 'Deploy and interact with smart contracts using Thirdweb SDK on Superposition L3',
    category: 'app',
    tags: ['superposition', 'thirdweb', 'contracts', 'deploy', 'nft', 'token'],
  };

  readonly configSchema = SuperpositionThirdwebConfig as unknown as z.ZodType<z.infer<typeof SuperpositionThirdwebConfig>>;

  readonly ports: PluginPort[] = [
    {
      id: 'network-in',
      name: 'Network Config',
      type: 'input',
      dataType: 'config',
    },
    {
      id: 'thirdweb-out',
      name: 'Thirdweb Config',
      type: 'output',
      dataType: 'config',
    },
    {
      id: 'contracts-out',
      name: 'Contract Helpers',
      type: 'output',
      dataType: 'api',
    },
  ];

  getDefaultConfig(): Partial<z.infer<typeof SuperpositionThirdwebConfig>> {
    return {
      features: ['deploy-contract', 'contract-interaction'],
      generateThirdwebProvider: true,
      generateDeployHelpers: true,
      generateContractHooks: true,
      includePrebuiltContracts: true,
      gasless: false,
    };
  }

  async generate(
    node: BlueprintNode,
    context: ExecutionContext
  ): Promise<CodegenOutput> {
    const config = this.configSchema.parse(node.config);
    const output = this.createEmptyOutput();

    // Generate types
    this.addFile(output, 'thirdweb.ts', generateThirdwebTypes(), 'frontend-types');

    // Generate Thirdweb configuration
    this.addFile(output, 'thirdweb-config.ts', generateThirdwebConfig(), 'frontend-lib');

    // Generate deploy hook
    if (config.generateDeployHelpers) {
      this.addFile(output, 'useThirdwebSuperposition.ts', generateDeployHook(config), 'frontend-hooks');
    }

    // Generate contract interaction hook
    if (config.generateContractHooks) {
      this.addFile(output, 'useSuperpositionContract.ts', generateContractHook(), 'frontend-hooks');
    }

    // Generate provider component
    if (config.generateThirdwebProvider) {
      this.addFile(output, 'SuperpositionThirdwebProvider.tsx', generateThirdwebProvider(), 'frontend-components');
    }

    // Generate prebuilt contracts helpers
    if (config.includePrebuiltContracts) {
      this.addFile(output, 'prebuilt-contracts.ts', generatePrebuiltContracts(), 'frontend-lib');
    }

    // Generate index file
    this.addFile(output, 'thirdweb-index.ts', generateIndexFile(config), 'frontend-lib');

    // Add environment variables
    this.addEnvVar(
      output,
      'NEXT_PUBLIC_THIRDWEB_CLIENT_ID',
      'Thirdweb client ID from https://thirdweb.com/dashboard',
      { required: true }
    );

    // Add documentation
    this.addDoc(
      output,
      'docs/superposition/thirdweb.md',
      'Thirdweb on Superposition',
      generateThirdwebDocs(config)
    );

    context.logger.info('Generated Thirdweb on Superposition integration', {
      nodeId: node.id,
      features: config.features,
    });

    return output;
  }
}

/**
 * Generate index file for Thirdweb exports
 */
function generateIndexFile(config: z.infer<typeof SuperpositionThirdwebConfig>): string {
  return `// Thirdweb on Superposition - Index
// Generated by [N]skills - https://www.nskills.xyz

// Configuration
export * from './thirdweb';
${config.includePrebuiltContracts ? "export * from './prebuilt-contracts';" : ''}

// Types
export * from '../types/thirdweb';
`;
}
