import { z } from 'zod';
import {
  BasePlugin,
  type PluginMetadata,
  type PluginPort,
  type CodegenOutput,
  type BlueprintNode,
  type ExecutionContext,
} from '@dapp-forge/plugin-sdk';
import { SuperpositionBridgeConfig } from '@dapp-forge/blueprint-schema';
import {
  generateBridgeTypes,
  generateBridgeHook,
  generateWithdrawHook,
  generateBridgeUI,
  generateBridgeDocs,
} from './templates';

/**
 * Superposition Bridge Plugin
 * Generates bridge integration for Superposition L3 via Li.Fi
 */
export class SuperpositionBridgePlugin extends BasePlugin<z.infer<typeof SuperpositionBridgeConfig>> {
  readonly metadata: PluginMetadata = {
    id: 'superposition-bridge',
    name: 'Superposition Bridge',
    version: '0.1.0',
    description: 'Bridge assets to Superposition L3 via Li.Fi/Stargate',
    category: 'app',
    tags: ['superposition', 'bridge', 'lifi', 'cross-chain', 'l3'],
  };

  readonly configSchema = SuperpositionBridgeConfig as unknown as z.ZodType<z.infer<typeof SuperpositionBridgeConfig>>;

  readonly ports: PluginPort[] = [
    {
      id: 'network-in',
      name: 'Network Config',
      type: 'input',
      dataType: 'config',
      required: false,
    },
    {
      id: 'bridge-hooks-out',
      name: 'Bridge Hooks',
      type: 'output',
      dataType: 'api',
    },
  ];

  getDefaultConfig(): Partial<z.infer<typeof SuperpositionBridgeConfig>> {
    return {
      bridgeProvider: 'lifi',
      supportedTokens: ['ETH', 'USDC'],
      sourceChains: ['arbitrum'],
      generateUI: true,
      generateHooks: true,
      enableWithdraw: true,
      slippageTolerance: 0.5,
    };
  }

  async generate(
    node: BlueprintNode,
    context: ExecutionContext
  ): Promise<CodegenOutput> {
    const config = this.configSchema.parse(node.config);
    const output = this.createEmptyOutput();

    // Generate types
    this.addFile(
      output,
      'bridge.ts',
      generateBridgeTypes(config),
      'frontend-types'
    );

    // Generate hooks
    if (config.generateHooks) {
      this.addFile(
        output,
        'useSuperpositionBridge.ts',
        generateBridgeHook(config),
        'frontend-hooks'
      );

      if (config.enableWithdraw) {
        const withdrawHook = generateWithdrawHook(config);
        if (withdrawHook) {
          this.addFile(
            output,
            'useSuperpositionWithdraw.ts',
            withdrawHook,
            'frontend-hooks'
          );
        }
      }
    }

    // Generate UI component
    if (config.generateUI) {
      const bridgeUI = generateBridgeUI(config);
      if (bridgeUI) {
        this.addFile(
          output,
          'SuperpositionBridge.tsx',
          bridgeUI,
          'frontend-components'
        );
      }
    }

    // Generate index file
    this.addFile(
      output,
      'superposition-bridge.ts',
      generateIndexFile(config),
      'frontend-lib'
    );

    // Add dependencies note
    output.docs.push({
      path: 'docs/superposition/bridge-setup.md',
      title: 'Bridge Setup',
      content: `## Dependencies

Install the Li.Fi SDK:

\`\`\`bash
pnpm add @lifi/sdk
\`\`\`

## Environment Variables

No additional environment variables required for basic bridge functionality.
`,
    });

    // Add environment variables
    this.addEnvVar(output, 'NEXT_PUBLIC_LIFI_INTEGRATOR', 'Li.Fi integrator ID for bridge', {
      required: false,
      defaultValue: 'cradle-superposition-bridge',
    });

    // Add documentation
    this.addDoc(
      output,
      'docs/superposition/bridge.md',
      'Superposition Bridge',
      generateBridgeDocs(config)
    );

    // Add scripts
    this.addScript(output, 'bridge:test', 'echo "Bridge integration ready"', 'Test bridge setup');

    context.logger.info('Generated Superposition bridge integration', {
      nodeId: node.id,
      provider: config.bridgeProvider,
      sourceChains: config.sourceChains,
    });

    return output;
  }
}

/**
 * Generate index file for bridge exports
 */
function generateIndexFile(config: z.infer<typeof SuperpositionBridgeConfig>): string {
  return `// Superposition Bridge Exports
// Generated by [N]skills - https://www.nskills.xyz

export * from './useSuperpositionBridge';
${config.enableWithdraw ? "export * from './useSuperpositionWithdraw';" : ''}
export * from '../types/bridge';
`;
}
