export const BNB_NETWORKS = {
  testnet: {
    id: 'testnet' as const,
    name: 'BNB Smart Chain Testnet',
    chainId: 97,
    rpcUrl: 'https://data-seed-prebsc-1-s1.bnbchain.org:8545',
    explorerUrl: 'https://testnet.bscscan.com',
    label: 'BNB Testnet',
    description: 'BNB Smart Chain Testnet (BSC Testnet)',
    disabled: false,
    symbol: 'tBNB',
    nativeCurrency: {
      name: 'BNB',
      symbol: 'tBNB',
      decimals: 18,
    },
  },
  mainnet: {
    id: 'mainnet' as const,
    name: 'BSC Mainnet',
    chainId: 56,
    rpcUrl: 'https://bsc-dataseed.bnbchain.org',
    explorerUrl: 'https://bscscan.com',
    label: 'BNB Mainnet',
    description: 'BNB Smart Chain Mainnet',
    disabled: true,
    symbol: 'BNB',
    nativeCurrency: {
      name: 'BNB',
      symbol: 'BNB',
      decimals: 18,
    },
  },
  opbnbTestnet: {
    id: 'opbnbTestnet' as const,
    name: 'opBNB Testnet',
    chainId: 5611,
    rpcUrl: 'https://opbnb-testnet-rpc.bnbchain.org',
    explorerUrl: 'https://testnet.opbnbscan.com',
    label: 'opBNB Testnet',
    description: 'opBNB L2 Testnet',
    disabled: true,
    symbol: 'tBNB',
    nativeCurrency: {
      name: 'BNB',
      symbol: 'tBNB',
      decimals: 18,
    },
  },
  opbnbMainnet: {
    id: 'opbnbMainnet' as const,
    name: 'opBNB Mainnet',
    chainId: 204,
    rpcUrl: 'https://opbnb-mainnet-rpc.bnbchain.org',
    explorerUrl: 'https://opbnbscan.com',
    label: 'opBNB Mainnet',
    description: 'opBNB L2 Mainnet',
    disabled: true,
    symbol: 'BNB',
    nativeCurrency: {
      name: 'BNB',
      symbol: 'BNB',
      decimals: 18,
    },
  },
} as const;

export type BnbNetworkKey = keyof typeof BNB_NETWORKS;