import { z } from 'zod';
import {
  BasePlugin,
  type PluginMetadata,
  type PluginPort,
  type CodegenOutput,
  type BlueprintNode,
  type ExecutionContext,
} from '@dapp-forge/plugin-sdk';
import { SuperpositionMeowDomainsConfig } from '@dapp-forge/blueprint-schema';
import {
  generateMeowDomainsTypes,
  generateMeowDomainsConstants,
  generateMeowDomainsABIs,
  generateResolverHook,
  generateRegistrationHook,
  generateReverseLookupHook,
  generateDomainDisplay,
  generateMeowDomainsDocs,
} from './templates';

/**
 * Superposition Meow Domains Plugin
 * Web3 identity with .meow domain registration and resolution
 */
export class SuperpositionMeowDomainsPlugin extends BasePlugin<z.infer<typeof SuperpositionMeowDomainsConfig>> {
  readonly metadata: PluginMetadata = {
    id: 'superposition-meow-domains',
    name: 'Meow Domains',
    version: '0.1.0',
    description: 'Web3 identity layer with .meow domain registration and resolution on Superposition',
    category: 'app',
    tags: ['superposition', 'domains', 'identity', 'punk-domains', 'naming'],
  };

  readonly configSchema = SuperpositionMeowDomainsConfig as unknown as z.ZodType<z.infer<typeof SuperpositionMeowDomainsConfig>>;

  readonly ports: PluginPort[] = [
    {
      id: 'network-in',
      name: 'Network Config',
      type: 'input',
      dataType: 'config',
    },
    {
      id: 'domains-out',
      name: 'Domain Resolution',
      type: 'output',
      dataType: 'code',
    },
  ];

  getDefaultConfig(): Partial<z.infer<typeof SuperpositionMeowDomainsConfig>> {
    return {
      features: ['resolve', 'metadata'],
      generateResolverHook: true,
      generateRegistrationHook: false,
      generateDomainDisplay: true,
      supportedMetadata: ['twitter', 'url', 'avatar'],
    };
  }

  async generate(
    node: BlueprintNode,
    context: ExecutionContext
  ): Promise<CodegenOutput> {
    const config = this.configSchema.parse(node.config);
    const output = this.createEmptyOutput();

    // Generate types
    this.addFile(output, 'meow-domains.ts', generateMeowDomainsTypes(), 'frontend-types');

    // Generate constants and ABIs
    this.addFile(output, 'meow-domains-constants.ts', generateMeowDomainsConstants(), 'frontend-lib');
    this.addFile(output, 'meow-domains-abi.ts', generateMeowDomainsABIs(), 'frontend-lib');

    // Generate resolver hook
    if (config.generateResolverHook || config.features.includes('resolve')) {
      this.addFile(
        output,
        'useMeowDomain.ts',
        generateResolverHook(config),
        'frontend-hooks'
      );
    }

    // Generate registration hook
    if (config.generateRegistrationHook || config.features.includes('register')) {
      this.addFile(
        output,
        'useRegisterMeowDomain.ts',
        generateRegistrationHook(),
        'frontend-hooks'
      );
    }

    // Generate reverse lookup hook
    if (config.features.includes('reverse-lookup')) {
      this.addFile(
        output,
        'useMeowReverseLookup.ts',
        generateReverseLookupHook(),
        'frontend-hooks'
      );
    }

    // Generate domain display component
    if (config.generateDomainDisplay) {
      this.addFile(
        output,
        'MeowDomainDisplay.tsx',
        generateDomainDisplay(),
        'frontend-components'
      );
    }

    // Generate index file
    this.addFile(
      output,
      'meow-domains-index.ts',
      generateIndexFile(config),
      'frontend-lib'
    );

    // Add documentation
    this.addDoc(
      output,
      'docs/superposition/meow-domains.md',
      'Meow Domains (.meow)',
      generateMeowDomainsDocs(config)
    );

    context.logger.info('Generated Superposition Meow Domains integration', {
      nodeId: node.id,
      features: config.features,
    });

    return output;
  }
}

/**
 * Generate index file for Meow Domains exports
 */
function generateIndexFile(config: z.infer<typeof SuperpositionMeowDomainsConfig>): string {
  return `// Superposition Meow Domains - Index
// Generated by [N]skills - https://www.nskills.xyz

// Configuration
export * from './meow-domains-constants';
export * from './meow-domains-abi';

// Types
export * from '../types/meow-domains';
`;
}
