import { z } from 'zod';
import {
  BasePlugin,
  type PluginMetadata,
  type PluginPort,
  type CodegenOutput,
  type BlueprintNode,
  type ExecutionContext,
} from '@dapp-forge/plugin-sdk';
import { RobinhoodNetworkConfig } from '@dapp-forge/blueprint-schema';
import {
  generateChainConfig,
  generateConstants,
  generateNetworkSwitcherHook,
  generateWagmiConfig,
  generateDocs,
} from './templates';

/**
 * Robinhood Network Plugin
 * Generates chain configuration and utilities for Robinhood Chain testnet
 */
export class RobinhoodNetworkPlugin extends BasePlugin<z.infer<typeof RobinhoodNetworkConfig>> {
  readonly metadata: PluginMetadata = {
    id: 'robinhood-network',
    name: 'Robinhood Network',
    version: '0.1.0',
    description: 'Chain configuration and network utilities for Robinhood Chain testnet',
    category: 'app',
    tags: ['robinhood', 'orbit', 'arbitrum', 'chain-config', 'network', 'l2'],
  };

  readonly configSchema = RobinhoodNetworkConfig as unknown as z.ZodType<z.infer<typeof RobinhoodNetworkConfig>>;

  readonly ports: PluginPort[] = [
    { id: 'chain-config-out', name: 'Chain Config', type: 'output', dataType: 'config' },
    { id: 'constants-out', name: 'Contract Constants', type: 'output', dataType: 'config' },
  ];

  getDefaultConfig(): Partial<z.infer<typeof RobinhoodNetworkConfig>> {
    return {
      network: 'testnet',
      includeFaucetLink: true,
      generateChainConfig: true,
      generateConstants: true,
      enableWebSocket: true,
      generateNetworkSwitcher: true,
    };
  }

  async generate(node: BlueprintNode, context: ExecutionContext): Promise<CodegenOutput> {
    const config = this.configSchema.parse(node.config);
    const output = this.createEmptyOutput();

    if (config.generateChainConfig) {
      this.addFile(output, 'chains.ts', generateChainConfig(config), 'frontend-lib');
      this.addFile(output, 'wagmi-robinhood.ts', generateWagmiConfig(config), 'frontend-lib');
    }

    if (config.generateConstants) {
      this.addFile(output, 'robinhood-constants.ts', generateConstants(config), 'frontend-lib');
    }

    if (config.generateNetworkSwitcher) {
      this.addFile(output, 'useRobinhoodNetwork.ts', generateNetworkSwitcherHook(config), 'frontend-hooks');
    }

    this.addFile(
      output,
      'robinhood.ts',
      '// Robinhood Configuration Index\n// Generated by [N]skills - https://www.nskills.xyz\n\nexport * from \'./chains\';\nexport * from \'./robinhood-constants\';\nexport * from \'./wagmi-robinhood\';\n',
      'frontend-lib'
    );

    this.addEnvVar(output, 'NEXT_PUBLIC_ROBINHOOD_NETWORK', 'Robinhood network (testnet)', {
      required: false,
      defaultValue: 'testnet',
    });

    if (config.customRpcUrl) {
      this.addEnvVar(output, 'ROBINHOOD_RPC_URL', 'Custom Robinhood RPC URL', {
        required: false,
        defaultValue: config.customRpcUrl,
      });
    }

    this.addDoc(output, 'docs/robinhood/network.md', 'Robinhood Chain Integration', generateDocs(config));

    context.logger.info('Generated Robinhood network configuration', { nodeId: node.id });

    return output;
  }
}
