import type { z } from 'zod';
import type { RobinhoodNetworkConfig } from '@dapp-forge/blueprint-schema';
import { dedent } from '@dapp-forge/plugin-sdk';

type Config = z.infer<typeof RobinhoodNetworkConfig>;

const ROBINHOOD_TESTNET = {
  chainId: 46630,
  name: 'Robinhood Chain Testnet',
  rpcUrl: 'https://rpc.testnet.chain.robinhood.com',
  wsUrl: 'wss://feed.testnet.chain.robinhood.com',
  explorerUrl: 'https://explorer.testnet.chain.robinhood.com',
  nativeCurrency: { name: 'ETH', symbol: 'ETH', decimals: 18 },
};

export function generateChainConfig(config: Config): string {
  const customRpc = config.customRpcUrl;
  const enableWs = config.enableWebSocket;

  return dedent(`
    // Robinhood Chain Testnet Configuration
    // Generated by [N]skills - https://www.nskills.xyz

    import { defineChain } from 'viem';

    /**
     * Robinhood Chain Testnet (Chain ID: 46630)
     * Arbitrum Orbit L2 with ETH as native gas token
     */
    export const robinhoodTestnet = defineChain({
      id: 46630,
      name: 'Robinhood Chain Testnet',
      nativeCurrency: {
        name: 'ETH',
        symbol: 'ETH',
        decimals: 18,
      },
      rpcUrls: {
        default: {
          http: ['${customRpc || ROBINHOOD_TESTNET.rpcUrl}'],
          ${enableWs ? `webSocket: ['${ROBINHOOD_TESTNET.wsUrl}'],` : ''}
        },
        public: {
          http: ['${ROBINHOOD_TESTNET.rpcUrl}'],
          ${enableWs ? `webSocket: ['${ROBINHOOD_TESTNET.wsUrl}'],` : ''}
        },
      },
      blockExplorers: {
        default: {
          name: 'Robinhood Explorer',
          url: '${ROBINHOOD_TESTNET.explorerUrl}',
        },
      },
      testnet: true,
    });

    export const robinhoodChains = [robinhoodTestnet] as const;
    export type RobinhoodChainId = 46630;
  `);
}

export function generateConstants(config: Config): string {
  return dedent(`
    // Robinhood Chain Contract Addresses
    // Generated by [N]skills - https://www.nskills.xyz
    // Source: Official Robinhood Chain documentation

    import type { Address } from 'viem';

    /**
     * Robinhood Chain Testnet (L2) Contract Addresses
     */
    export const ROBINHOOD_TESTNET_CONTRACTS = {
      // Token contracts
      WETH: '0x7943e237c7F95DA44E0301572D358911207852Fa' as Address,
      TSLA: '0xC9f9c86933092BbbfFF3CCb4b105A4A94bf3Bd4E' as Address,
      AMZN: '0x5884aD2f920c162CFBbACc88C9C51AA75eC09E02' as Address,
      PLTR: '0x1FBE1a0e43594b3455993B5dE5Fd0A7A266298d0' as Address,
      NFLX: '0x3b8262A63d25f0477c4DDE23F83cfe22Cb768C93' as Address,
      AMD: '0x71178BAc73cBeb415514eB542a8995b82669778d' as Address,

      // L2 bridge and gateways
      L2_GATEWAY_ROUTER: '0x77bF00A6A90c600f214b34BAFBB7918c0cF113A8' as Address,
      L2_ERC20_GATEWAY: '0x8689aFB9086734e12beA6b5DF541a1da252Ea32a' as Address,
      L2_WETH_GATEWAY: '0x5A8F55202A625D12FFCb76F857FE4563bC8Ce413' as Address,
      L2_WETH: '0x7943e237c7F95DA44E0301572D358911207852Fa' as Address,
      L2_PROXY_ADMIN: '0xE743e696B00789Ef489cF617477771764E9283a0' as Address,

      // Misc
      L2_MULTICALL: '0xa432504b6F04Cafe775b09D8AA92e8dbe41Ec7a8' as Address,
    } as const;

    export const ROBINHOOD_CONFIG = {
      testnet: {
        chainId: 46630,
        name: 'Robinhood Chain Testnet',
        rpcUrl: '${ROBINHOOD_TESTNET.rpcUrl}',
        wsUrl: '${ROBINHOOD_TESTNET.wsUrl}',
        explorerUrl: '${ROBINHOOD_TESTNET.explorerUrl}',
      },
    } as const;
  `);
}

export function generateNetworkSwitcherHook(config: Config): string {
  return dedent(`
    // Robinhood Network Switcher Hook
    // Generated by [N]skills - https://www.nskills.xyz

    'use client';

    import { useCallback, useMemo } from 'react';
    import { useChainId, useSwitchChain } from 'wagmi';
    import { robinhoodTestnet } from '../lib/chains';

    export type RobinhoodNetwork = 'testnet';

    export function useRobinhoodNetwork() {
      const chainId = useChainId();
      const { switchChain, isPending, error } = useSwitchChain();

      const currentNetwork = useMemo((): RobinhoodNetwork | null => {
        if (chainId === 46630) return 'testnet';
        return null;
      }, [chainId]);

      const isOnRobinhood = currentNetwork !== null;

      const switchToRobinhood = useCallback(
        async () => {
          await switchChain({ chainId: robinhoodTestnet.id });
        },
        [switchChain]
      );

      return {
        currentNetwork,
        isOnRobinhood,
        isSwitching: isPending,
        switchError: error,
        switchToRobinhood,
        chainId,
      };
    }

    export function getRobinhoodExplorerUrl(txHash: string): string {
      return \`${ROBINHOOD_TESTNET.explorerUrl}/tx/\${txHash}\`;
    }

    export function getRobinhoodAddressUrl(address: string): string {
      return \`${ROBINHOOD_TESTNET.explorerUrl}/address/\${address}\`;
    }
  `);
}

export function generateWagmiConfig(config: Config): string {
  const enableWs = config.enableWebSocket;

  return dedent(`
    // Robinhood Wagmi Configuration
    // Generated by [N]skills - https://www.nskills.xyz

    import { http${enableWs ? ', webSocket' : ''} } from 'wagmi';
    import { robinhoodTestnet } from './chains';

    export const robinhoodTransports = {
      [robinhoodTestnet.id]: ${enableWs ? `webSocket('${ROBINHOOD_TESTNET.wsUrl}')` : `http('${ROBINHOOD_TESTNET.rpcUrl}')`},
    } as const;

    export const robinhoodChainsConfig = [robinhoodTestnet] as const;
  `);
}

export function generateDocs(config: Config): string {
  const withFaucet = config.includeFaucetLink;
  return dedent(`
    # Robinhood Chain Integration

    This module provides configuration for the Robinhood Chain testnet.

    ## Overview

    Robinhood Chain Testnet is an Arbitrum Orbit Layer 2 built on Ethereum, using ETH as the native gas token.

    ## Network Details

    - **Chain ID**: 46630
    - **RPC URL**: https://rpc.testnet.chain.robinhood.com
    - **WebSocket**: wss://feed.testnet.chain.robinhood.com
    - **Explorer**: https://explorer.testnet.chain.robinhood.com
    ${withFaucet ? '- **Faucet**: Deposit testnet funds via the official faucet or bridge Sepolia ETH' : ''}

    ## Usage

    \`\`\`typescript
    import { robinhoodTestnet } from './lib/chains';
    import { createConfig } from 'wagmi';

    const config = createConfig({
      chains: [robinhoodTestnet],
      // ... other config
    });
    \`\`\`

    ## Resources

    - [Robinhood Chain Explorer](https://explorer.testnet.chain.robinhood.com)
  `);
}
